import { Project, Tool, FeaturedWorld } from "./types";

export const FEATURED_WORLDS: FeaturedWorld[] = [
  {
    id: "merge-hometown",
    title: "Merge HomeTown",
    image: "https://play-lh.googleusercontent.com/BTxW1F_ZMAgKN47e2wTZW--h6_OwgiVNS0yKP2N3oRWSu-fvzUQozidaI2Z7gAOcxfdFgF0WRNQevFEIyVhHqw",
    description: "A successful casual mobile title featuring intricate 2D/3D environments and engaging merge mechanics.",
    link: "https://play.google.com/store/search?q=Merge+HomeTown&c=apps",
  },
  {
    id: "tales-dragons",
    title: "Tales & Dragons: Merge Puzzle",
    image: "https://play-lh.googleusercontent.com/-FrcJNYIXaoMIMZaFEEBUoYyIIgH8RceoMIiXg1zWDuWJWG-g9gC3_JYy_VldTj_Og",
    description: "Whimsical merge puzzle game with stylized character designs and magical forest themes.",
    link: "https://play.google.com/store/apps/details?id=com.dragontales.mergegames",
  },
  {
    id: "call-of-legends",
    title: "Call of Legends: RPG TD Game",
    image: "https://play-lh.googleusercontent.com/nz4cBSiLfZK_gndFVvh6TP_Oda_SXd6fBBgpCnhctOWW6gesfU2qtsxP5Zv3flAw3S0T1ABhwa1G8YnaUEJu",
    description: "Strategic tower defense game with high-quality 3D models and intense visual effects.",
    link: "https://play.google.com/store/apps/details?id=com.gamestown.tower.defense",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "merge-hometown",
    title: "Merge HomeTown: Merge Games",
    category: "Merge",
    image: "https://play-lh.googleusercontent.com/BTxW1F_ZMAgKN47e2wTZW--h6_OwgiVNS0yKP2N3oRWSu-fvzUQozidaI2Z7gAOcxfdFgF0WRNQevFEIyVhHqw",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/search?q=Merge+HomeTown&c=apps",
  },
  {
    id: "merge-fever",
    title: "Merge Fever: Merge Games",
    category: "Merge",
    image: "https://play-lh.googleusercontent.com/jnAdtgmG3F-HmhNmZnboA6HOqZKnyfa8T1Dxf1_lgworr5JEjR-NRWu1mq8JzWIDr5U",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/search?q=Merge+Fever&c=apps",
  },
  {
    id: "hexa-fever",
    title: "Hexa Fever: Color Sort Puzzle",
    category: "Puzzle & Sort",
    image: "https://play-lh.googleusercontent.com/45QtXkJq2I8YxQKlD9DuV6jub68ROBLgqZrm0a-2Kfw2KCzoqPWcU9eLQ6AnLlLwWw",
    tools: ["Photoshop", "Procreate"],
    link: "https://play.google.com/store/search?q=Hexa+Fever&c=apps",
  },
  {
    id: "sherlock-merge",
    title: "Sherlock: Mystry Merge",
    category: "Merge",
    image: "https://play-lh.googleusercontent.com/EhthOkRbvG4tQXJANWW40ddQYlQDLehIoVBVv2fLsuVktdl90wFYdX_FsOEkIKHT1X8",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/search?q=Sherlock+Merge&c=apps",
  },
  {
    id: "candy-sort",
    title: "Candy Sort: Triple Match",
    category: "Puzzle & Sort",
    image: "https://play-lh.googleusercontent.com/sYzYwjDiL5IgsbyCXLQrNzDOpS3-K5EcO3WKtODu_XRUpLXhwpDXFFrfJBFM6d9JDVCG",
    tools: ["Procreate", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.gamestown.candy.sortgames",
  },
  {
    id: "tales-dragons",
    title: "Tales & Dragons: Merge Puzzle",
    category: "Merge",
    image: "https://play-lh.googleusercontent.com/-FrcJNYIXaoMIMZaFEEBUoYyIIgH8RceoMIiXg1zWDuWJWG-g9gC3_JYy_VldTj_Og",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.dragontales.mergegames",
  },
  {
    id: "wizard-world",
    title: "Wizard World: Magic Merge",
    category: "Merge",
    image: "https://play-lh.googleusercontent.com/BFQMMEHdWaLcD44XKbJ41yJpERoX70av01lmNt6HGpThyw7jIu6WEgrCLQ5VYj99tMw",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.wizardschool.magic.merge",
  },
  {
    id: "call-of-legends",
    title: "Call of Legends: RPG TD Game",
    category: "Tower Defense",
    image: "https://play-lh.googleusercontent.com/nz4cBSiLfZK_gndFVvh6TP_Oda_SXd6fBBgpCnhctOWW6gesfU2qtsxP5Zv3flAw3S0T1ABhwa1G8YnaUEJu",
    tools: ["Blender", "Affinity Designer"],
    link: "https://play.google.com/store/apps/details?id=com.gamestown.tower.defense",
  },
  {
    id: "epic-merge",
    title: "Epic Merge: Magic Match Puzzle",
    category: "Merge",
    image: "https://play-lh.googleusercontent.com/YdWpQ7PZLdY12-wDyVg9c3xcEdns8PZFEMtegO5U-PdBlS5hqOy-ZcwTZMuJSY2anKQ",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.matchingham.mergegame",
  },
  {
    id: "knit-sort",
    title: "Knit Sort Jam",
    category: "Puzzle & Sort",
    image: "https://play-lh.googleusercontent.com/Xt8k3pjaUDRinMWmUQlkeTsUdIof5Z6vHhkohMZxAvjFNZ9Q0McQYkj8wuqJJc72nZmM6g_ZSZUScteAnGTN6g",
    tools: ["Photoshop", "Procreate"],
    link: "https://play.google.com/store/apps/details?id=com.knitbusjam.sortpuzzle",
  },
  {
    id: "thread-color",
    title: "Thread Color: Block Jam Puzzle",
    category: "Puzzle & Sort",
    image: "https://play-lh.googleusercontent.com/-hgA-8sgXCTsndbI2PUGbyhxqTuvhz7n2GbPsD0ELGZ_oStl288lyL9Uq-0kdtF1Q92wzLiHIOkQ67QSQ7qyRw",
    tools: ["Photoshop", "Procreate"],
    link: "https://play.google.com/store/apps/details?id=com.threadcolor.blockjampuzzle",
  },
  {
    id: "idle-cityscape",
    title: "Idle Cityscape Tycoon",
    category: "Idle & Tycoon",
    image: "https://play-lh.googleusercontent.com/kw_SixxDOAIht083Ulp463-s4qvnf8nQmCf6cdus1RquZ1IRIecvl936HJYkMsh3Ug",
    tools: ["Photoshop", "Generative AI"],
    link: "https://play.google.com/store/search?q=Idle+Cityscape+Tycoon&c=apps",
  },
  {
    id: "pinball-smash",
    title: "Pinball - Smash & Hit",
    category: "Arcade",
    image: "https://play-lh.googleusercontent.com/bNPvfkhfDOIV7dG3d19sJvv04_UUcF7EKnCLLsYAKA3H0NNFxhX5hM4yn3_5lRwSvtY",
    tools: ["Blender", "Photoshop"],
    link: "https://play-lh.googleusercontent.com/bNPvfkhfDOIV7dG3d19sJvv04_UUcF7EKnCLLsYAKA3H0NNFxhX5hM4yn3_5lRwSvtY",
  },
];

export const TOOLS: Tool[] = [
  { name: "Adobe Photoshop", icon: "Image", color: "#31A8FF" },
  { name: "Blender 3D", icon: "Box", color: "#F5792A" },
  { name: "Generative AI", icon: "Sparkles", color: "#FFD700" },
  { name: "Procreate", icon: "Brush", color: "#E1306C" },
  { name: "Affinity Designer", icon: "Spline", color: "#5F259F" },
];
