import { Project, Tool, FeaturedWorld } from "./types";

export const FEATURED_WORLDS: FeaturedWorld[] = [
  {
    id: "merge-hometown",
    title: "Merge HomeTown",
    image: "https://picsum.photos/seed/hometown/1200/600",
    description: "A successful casual mobile title featuring intricate 2D/3D environments and engaging merge mechanics.",
    link: "https://play.google.com/store/search?q=Merge+HomeTown&c=apps",
  },
  {
    id: "tales-dragons",
    title: "Tales & Dragons: Merge Puzzle",
    image: "https://picsum.photos/seed/dragons/1200/600",
    description: "Whimsical merge puzzle game with stylized character designs and magical forest themes.",
    link: "https://play.google.com/store/apps/details?id=com.dragontales.mergegames",
  },
  {
    id: "call-of-legends",
    title: "Call of Legends: RPG TD Game",
    image: "https://picsum.photos/seed/legends/1200/600",
    description: "Strategic tower defense game with high-quality 3D models and intense visual effects.",
    link: "https://play.google.com/store/apps/details?id=com.gamestown.tower.defense",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "merge-hometown",
    title: "Merge HomeTown: Merge Games",
    category: "Merge",
    image: "https://picsum.photos/seed/hometown/600/400",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/search?q=Merge+HomeTown&c=apps",
  },
  {
    id: "merge-fever",
    title: "Merge Fever: Merge Games",
    category: "Merge",
    image: "https://picsum.photos/seed/fever/600/400",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/search?q=Merge+Fever&c=apps",
  },
  {
    id: "hexa-fever",
    title: "Hexa Fever: Color Sort Puzzle",
    category: "Puzzle & Sort",
    image: "https://picsum.photos/seed/hexa/600/400",
    tools: ["Photoshop", "Procreate"],
    link: "https://play.google.com/store/search?q=Hexa+Fever&c=apps",
  },
  {
    id: "sherlock-merge",
    title: "Sherlock: Mystry Merge",
    category: "Merge",
    image: "https://picsum.photos/seed/sherlock/600/400",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/search?q=Sherlock+Merge&c=apps",
  },
  {
    id: "candy-sort",
    title: "Candy Sort: Triple Match",
    category: "Puzzle & Sort",
    image: "https://picsum.photos/seed/candy/600/400",
    tools: ["Procreate", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.gamestown.candy.sortgames",
  },
  {
    id: "tales-dragons",
    title: "Tales & Dragons: Merge Puzzle",
    category: "Merge",
    image: "https://picsum.photos/seed/dragons/600/400",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.dragontales.mergegames",
  },
  {
    id: "wizard-world",
    title: "Wizard World: Magic Merge",
    category: "Merge",
    image: "https://picsum.photos/seed/wizard/600/400",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.wizardschool.magic.merge",
  },
  {
    id: "call-of-legends",
    title: "Call of Legends: RPG TD Game",
    category: "Tower Defense",
    image: "https://picsum.photos/seed/legends/600/400",
    tools: ["Blender", "Affinity Designer"],
    link: "https://play.google.com/store/apps/details?id=com.gamestown.tower.defense",
  },
  {
    id: "epic-merge",
    title: "Epic Merge: Magic Match Puzzle",
    category: "Merge",
    image: "https://picsum.photos/seed/epic/600/400",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/apps/details?id=com.matchingham.mergegame",
  },
  {
    id: "knit-sort",
    title: "Knit Sort Jam",
    category: "Puzzle & Sort",
    image: "https://picsum.photos/seed/knit/600/400",
    tools: ["Photoshop", "Procreate"],
    link: "https://play.google.com/store/apps/details?id=com.knitbusjam.sortpuzzle",
  },
  {
    id: "thread-color",
    title: "Thread Color: Block Jam Puzzle",
    category: "Puzzle & Sort",
    image: "https://picsum.photos/seed/thread/600/400",
    tools: ["Photoshop", "Procreate"],
    link: "https://play.google.com/store/apps/details?id=com.threadcolor.blockjampuzzle",
  },
  {
    id: "idle-cityscape",
    title: "Idle Cityscape Tycoon",
    category: "Idle & Tycoon",
    image: "https://picsum.photos/seed/cityscape/600/400",
    tools: ["Photoshop", "Generative AI"],
    link: "https://play.google.com/store/search?q=Idle+Cityscape+Tycoon&c=apps",
  },
  {
    id: "pinball-smash",
    title: "Pinball - Smash & Hit",
    category: "Arcade",
    image: "https://picsum.photos/seed/pinball/600/400",
    tools: ["Blender", "Photoshop"],
    link: "https://play.google.com/store/search?q=Pinball+Smash+Hit&c=apps",
  },
];

export const TOOLS: Tool[] = [
  { name: "Adobe Photoshop", icon: "Image", color: "#31A8FF" },
  { name: "Blender 3D", icon: "Box", color: "#F5792A" },
  { name: "Generative AI", icon: "Sparkles", color: "#FFD700" },
  { name: "Procreate", icon: "Brush", color: "#E1306C" },
  { name: "Affinity Designer", icon: "Spline", color: "#5F259F" },
];
